jobs:
    build:
        name: Build App
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.x]
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Use Node.js ${{matrix.node-version}}
              uses: actions/setup-node@v1
              with:
                node-version: ${{matrix.node-version}}
            - name: Install
              uses: yarn install --frozen-lockfile
            - name: Build
              uses: yarn run build --if-present
